name: MERN CD

On:
  Push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Deploy Via SSH
       uses: appleboy/ssh-action@v1
       with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd devops-mern-todo/
            git pull origin main
            docker-compose down
            docker-compose up --bulid -d
